export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  ASST_CHIEF_CONVENOR: 'ASST_CHIEF_CONVENOR',
  DEPT_CONVENOR: 'DEPT_CONVENOR',
  DEPT_ASST_CONVENOR: 'DEPT_ASST_CONVENOR',
  COORDINATOR: 'COORDINATOR',
  MEMBER: 'MEMBER'
};

export const APPROVAL_STATUS = {
  ACTIVE: 'ACTIVE',
  PENDING_DEPT_REVIEW: 'PENDING_DEPT_REVIEW',
  PENDING_ASST_CHIEF_REVIEW: 'PENDING_ASST_CHIEF_REVIEW',
  REJECTED: 'REJECTED'
};

export const EVENT_STATUS = {
  SCHEDULED: 'SCHEDULED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED'
};

export const REVIEW_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
};
